eureka.instance.hostname=localhost
# We do not want the discovery server to register itself as a client on eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL}
server.port=${SERVER_PORT}
spring.zipkin.base-url=${ZIPKIN_URL}
spring.sleuth.sampler.probability= 1.0